Qaft 673 banking flow
Fundthrough/ft-qa-automation pull request #14
Opened 2022-05-31 20:41 UTC by murad755

2022-06-21 22:45 UTC, Praisy02 requested changes

2022-06-21 22:45 UTC, Praisy02 commented on cypress/support/Helpers/common/messages.js
> +}
hey @murad755 : can you use checkMessage() method for validating agreement error ?

2022-06-21 22:45 UTC, Praisy02 commented on cypress/integration/nebula/bankingFlow.spec.js
> +        bankingFlowPage.checkCard('Add your bank', false)
can you handle the case if action card doesn;t exist ?

2022-06-22 19:47 UTC, murad755 commented on cypress/support/Helpers/common/messages.js
> +}
done

2022-06-22 19:47 UTC, murad755 commented on cypress/integration/nebula/bankingFlow.spec.js
> +        bankingFlowPage.checkCard('Add your bank', false)
done

2022-06-23 19:51 UTC, merged