refactoring of sign up spec flow
Fundthrough/ft-qa-automation pull request #8
Opened 2022-04-28 15:31 UTC by murad755

Refactoring Sign Up spec flow

2022-05-02 19:32 UTC, mikalai-okun-ft commented on cypress/integration/nebula/TC01_signUp.spec.js
> +import {SignUpPage, signUpSelectors, signUpTexts} from "../../support/Page_Objects/signUpPage.js";
Did you run the eslint/prettier?

2022-05-02 19:33 UTC, mikalai-okun-ft approved these changes

2022-05-04 09:29 UTC, murad755 commented on cypress/integration/nebula/TC01_signUp.spec.js
> +import {SignUpPage, signUpSelectors, signUpTexts} from "../../support/Page_Objects/signUpPage.js";
I couldn't find prettier in a project, but I used eslint.

2022-05-04 15:19 UTC, ManpreetChopraKaur reviewed
@murad755 change "Kristina" email to
"techadmin" + randomChars(4)+ "@fundthrough.com"
change "saksham+" to "techadmin"

2022-05-04 18:00 UTC, ManpreetChopraKaur approved these changes

2022-05-04 18:31 UTC, Praisy02 requested changes

2022-05-04 18:31 UTC, Praisy02 commented on cypress/support/Helpers/common/button.js
> +}
Can we add a common function for getError webElement?

2022-05-04 18:31 UTC, Praisy02 commented on cypress/support/Page_Objects/signUpPage.js
> +        cy.url().should('include', 'signup')
can you use the endpoint in cy.visit('/signup') and change the baseurl to https://nebula-qa1.fundthrough.com

2022-05-04 19:59 UTC, Praisy02 approved these changes

2022-05-06 14:56 UTC, merged